#serverless.yml
service: flask-warmup

provider:
  name: aws
  stage: dev
  region: ap-south-1
  ecr:
    images:
      appimage:
        path: ./

plugins:
  - serverless-plugin-warmup
  - serverless-apigw-binary


custom:
  apigwBinary:
    types: #list of mime-types
      - 'audio/wav'
      - 'multipart/form-data'
#  add restriction for api gateway
  warmup:
    officeHoursWarmer:
#      enabled: true
      events:
        - schedule: cron(0/5 2-14 ? * MON-SUN *)
      verbose: true
      logRetentionInDays: 14
      package:
        individually: true
        patterns:
#          - '!node_modules/**'
#          - '!venv/**'
          - './**'
  wsgi:
    app:app.app

functions:
  app:
    image:
      name: appimage
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    warmup:
      officeHoursWarmer:
        enabled: true