#serverless.yml
service: flask-warmup

provider:
  name: aws
  stage: dev
  region: ap-south-1
  ecr:
    images:
#      dockerslim:
#        pa
      appimage:
        path: ./

functions:
  app:
    image:
      name: appimage
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY /{proxy+}'
    warmup:
      officeHoursWarmer:
        enabled: true
#    provisionedConcurrency: 10


plugins:
  - serverless-plugin-warmup
#  - serverless-apigw-binary

custom:
  warmup:
    officeHoursWarmer:
      enabled: true
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *)
#      concurrency: 10
      verbose: true
      logRetentionInDays: 14
      package:
        individually: true
        patterns:
          - './**'
        exclude:
          - .git/**
          - '.git/**'
          - venv/**


#
#custom:
#  apigwBinary:
#    types: #list of mime-types
#      - 'audio/wav'
#      - 'multipart/form-data'